@AwsDotnetApp_HostAddress = http://localhost:5200

### Get all todos
GET {{AwsDotnetApp_HostAddress}}/todos
Accept: application/json

###

### Create a new todo
POST {{AwsDotnetApp_HostAddress}}/todos
Content-Type: application/json

{
  "title": "Test from .http"
}

###

### Get a specific todo by ID (change ID to real one)
GET {{AwsDotnetApp_HostAddress}}/todos/00000000-0000-0000-0000-000000000011
Accept: application/json

###

### Update a todo (change ID to real one)
PUT {{AwsDotnetApp_HostAddress}}/todos/00000000-0000-0000-0000-000000000011
Content-Type: application/json

{
  "id": "00000000-0000-0000-0000-000000000011",
  "title": "Updated title",
  "isDone": true
}

###

### Delete a todo
DELETE {{AwsDotnetApp_HostAddress}}/todos/00000000-0000-0000-0000-000000000011
