---
# Backend deployment
- name: Copy backend files
  synchronize:
    src: "{{ backend_src }}/"
    dest: "{{ backend_dir }}/"
  become: false

- name: Set permissions for backend
  file:
    path: "{{ backend_dir }}"
    recurse: yes
    mode: '0755'

- name: Create systemd service for backend API
  template:
    src: todo-api.service.j2
    dest: /etc/systemd/system/todo-api.service
  notify: Restart Backend API

- name: Enable and start backend API service
  systemd:
    name: todo-api
    state: started
    enabled: yes
    daemon_reload: yes