---
# Frontend deployment
- name: Copy frontend files
  synchronize:
    src: "{{ frontend_src }}/"
    dest: "{{ frontend_dir }}/"
  become: false

- name: Set permissions for frontend
  file:
    path: "{{ frontend_dir }}"
    owner: nginx
    group: nginx
    recurse: yes
    mode: '0755'

# NGINX configuration
- name: Ensure sites-available and sites-enabled directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - /etc/nginx/sites-available
    - /etc/nginx/sites-enabled

- name: Configure NGINX main config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: '0644'
  notify: Restart NGINX

- name: Configure NGINX site
  template:
    src: nginx-site.j2
    dest: /etc/nginx/sites-available/todo-app
    mode: '0644'
  notify: Restart NGINX

- name: Enable site configuration
  file:
    src: /etc/nginx/sites-available/todo-app
    dest: /etc/nginx/sites-enabled/todo-app
    state: link
  notify: Restart NGINX

- name: Enable and start NGINX
  systemd:
    name: nginx
    state: started
    enabled: yes