- name: Deploy ToDo App
  hosts: all
  become: true
  vars:
    frontend_src: ../frontend/build/
    backend_src: ../backend/publish/

  tasks:
    - name: Install dependencies for Microsoft repo
      yum:
        name:
          - wget
          - yum-utils
        state: present
        update_cache: yes

    - name: Add Microsoft Yum repo for .NET 9
      get_url:
        url: https://packages.microsoft.com/config/centos/7/prod.repo
        dest: /etc/yum.repos.d/microsoft-prod.repo

    - name: Install .NET SDK 9.0
      yum:
        name: dotnet-sdk-9.0
        state: present
        update_cache: yes

    - name: Install Nginx
      yum:
        name: nginx
        state: present
        update_cache: yes

    - name: Upload React frontend
      copy:
        src: "{{ frontend_src }}"
        dest: /var/www/html/
        owner: ec2-user
        group: nginx
        mode: 0755

    - name: Upload .NET backend
      copy:
        src: "{{ backend_src }}"
        dest: /opt/backend/
        mode: 0755

    - name: Start .NET API
      shell: "nohup dotnet /opt/backend/backend.dll &"

    - name: Configure Nginx
      copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
        mode: 0644
      notify: Restart nginx

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
