- name: Deploy ToDo App
  hosts: all
  become: true
  vars:
    frontend_src: ../frontend/build/
    backend_src: ../backend/publish/

  tasks:
    - name: Install dependencies for Amazon Linux 2023+
      when: ansible_distribution_version is version('2023', '>=')
      ansible.builtin.dnf:
        name:
          - nginx
          - dotnet-sdk-9.0
        state: present
        update_cache: yes
        use_backend: dnf5

    - name: Upload React frontend
      copy:
        src: "{{ frontend_src }}"
        dest: /var/www/html/
        mode: 0755

    - name: Upload .NET backend
      copy:
        src: "{{ backend_src }}"
        dest: /opt/backend/
        mode: 0755

    - name: Start .NET API
      shell: "nohup dotnet /opt/backend/backend.dll &"

    - name: Configure Nginx
      copy:
        src: nginx.conf
        dest: /etc/nginx/sites-available/default
        mode: 0644
      notify: Restart nginx

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
