- name: Deploy ToDo App
  hosts: all
  become: true
  vars:
    frontend_src: ../frontend/build/
    backend_src: ../backend/publish/

  tasks:
    - name: Import Microsoft GPG key
      ansible.builtin.command: >
        rpm --import https://packages.microsoft.com/keys/microsoft.asc

    - name: Add Microsoft yum repo
      ansible.builtin.command: >
        wget -O /etc/yum.repos.d/microsoft-prod.repo https://packages.microsoft.com/config/fedora/38/prod.repo

    - name: Install .NET SDK 9.0 and NGINX
      ansible.builtin.shell: |
        yum install -y dotnet-sdk-9.0
        amazon-linux-extras install nginx1
      args:
         executable: /bin/bash

    - name: Upload React frontend
      ansible.builtin.copy:
        src: "{{ frontend_src }}"
        dest: /var/www/html/
        mode: '0755'

    - name: Upload .NET backend
      ansible.builtin.copy:
        src: "{{ backend_src }}"
        dest: /opt/backend/
        mode: '0755'

    - name: Start .NET API
      ansible.builtin.shell: "nohup dotnet /opt/backend/AwsDotnetApp.dll &"
      args:
        chdir: /opt/backend/
        executable: /bin/bash

    - name: Configure Nginx
      ansible.builtin.copy:
        src: nginx.conf
        dest: /etc/nginx/sites-available/default
        mode: '0644'
      notify: Restart nginx

  handlers:
    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
