name: CI/CD Deploy To AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.0'

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform to create infrastructure
        id: terraform_apply
        run: |
          terraform apply -auto-approve
          echo "EC2_IP=$(terraform output -raw ec2_public_ip)" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        run: |
          npm install --global corepack@latest
          corepack enable pnpm
          corepack use pnpm@latest-10

      - name: Install dependencies & Build React
        working-directory: frontend
        run: |
          pnpm install
          pnpm build

      - name: Setup .NET & Build API
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Publish API
        working-directory: backend
        run: dotnet publish -c Release -o publish

      - name: Run Ansible
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/deploy.yml
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          inventory: |
            [all]
            ${{ env.EC2_IP }} ansible_user=ec2-user

