---
- name: Deploy Todo Application
  hosts: all
  become: true
  vars_files:
    - group_vars/all.yml
  
  tasks:
    - name: Include common tasks
      include_tasks: tasks/common.yml
      
    - name: Include backend deployment tasks
      include_tasks: tasks/backend.yml
      
    - name: Include frontend deployment tasks
      include_tasks: tasks/frontend.yml
  
  handlers:
    - import_tasks: handlers.yml