name: CI/CD Deploy To AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node & Build React
        working-directory: frontend
        run: |
          npm install
          npm run build

      - name: Setup .NET & Build API
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Publish API
        working-directory: backend
        run: dotnet publish -c Release -o publish


      - name: Run Ansible
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/deploy.yml
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          inventory: |
            [all]
            3.93.145.248 ansible_user=ec2-user
